
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:7 (project)"
    message: |
      The system is: Windows - 10.0.22621.0 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:7 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Versión de MSBuild 17.7.2+d6990bcfa para .NET Framework
      Compilación iniciada a las 3/9/2023 17:46:21.
      
      Proyecto "C:\\Users\\Jefe Maestro\\Desktop\\server\\CMakeFiles\\3.27.3\\CompilerIdC\\CompilerIdC.vcxproj" en nodo 1 (destinos predeterminados).
      PrepareForBuild:
        Creando directorio "Debug\\".
        Creando directorio "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Se creará "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" porque se especificó "AlwaysCreate".
        Aplicando tarea Touch a "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Users\\Jefe Maestro\\Desktop\\server\\CMakeFiles\\3.27.3\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Se eliminará el archivo "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
        Aplicando tarea Touch a "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Compilación del proyecto terminada "C:\\Users\\Jefe Maestro\\Desktop\\server\\CMakeFiles\\3.27.3\\CompilerIdC\\CompilerIdC.vcxproj" (destinos predeterminados).
      
      Compilación correcta.
          0 Advertencia(s)
          0 Errores
      
      Tiempo transcurrido 00:00:04.29
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/Jefe Maestro/Desktop/server/CMakeFiles/3.27.3/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:7 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Versión de MSBuild 17.7.2+d6990bcfa para .NET Framework
      Compilación iniciada a las 3/9/2023 17:46:27.
      
      Proyecto "C:\\Users\\Jefe Maestro\\Desktop\\server\\CMakeFiles\\3.27.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" en nodo 1 (destinos predeterminados).
      PrepareForBuild:
        Creando directorio "Debug\\".
        Creando directorio "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Se creará "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" porque se especificó "AlwaysCreate".
        Aplicando tarea Touch a "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Users\\Jefe Maestro\\Desktop\\server\\CMakeFiles\\3.27.3\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Se eliminará el archivo "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
        Aplicando tarea Touch a "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Compilación del proyecto terminada "C:\\Users\\Jefe Maestro\\Desktop\\server\\CMakeFiles\\3.27.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (destinos predeterminados).
      
      Compilación correcta.
          0 Advertencia(s)
          0 Errores
      
      Tiempo transcurrido 00:00:02.89
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/Jefe Maestro/Desktop/server/CMakeFiles/3.27.3/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:7 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/Jefe Maestro/Desktop/server/CMakeFiles/CMakeScratch/TryCompile-rc1aav"
      binary: "C:/Users/Jefe Maestro/Desktop/server/CMakeFiles/CMakeScratch/TryCompile-rc1aav"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
      CMAKE_C_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Jefe Maestro/Desktop/server/CMakeFiles/CMakeScratch/TryCompile-rc1aav'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_b837a.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        Versión de MSBuild 17.7.2+d6990bcfa para .NET Framework
        Compilación iniciada a las 3/9/2023 17:46:33.
        
        Proyecto "C:\\Users\\Jefe Maestro\\Desktop\\server\\CMakeFiles\\CMakeScratch\\TryCompile-rc1aav\\cmTC_b837a.vcxproj" en nodo 1 (destinos predeterminados).
        PrepareForBuild:
          Creando directorio "cmTC_b837a.dir\\Debug\\".
          Creando directorio "C:\\Users\\Jefe Maestro\\Desktop\\server\\CMakeFiles\\CMakeScratch\\TryCompile-rc1aav\\Debug\\".
          Creando directorio "cmTC_b837a.dir\\Debug\\cmTC_b837a.tlog\\".
        InitializeBuildStatus:
          Se creará "cmTC_b837a.dir\\Debug\\cmTC_b837a.tlog\\unsuccessfulbuild" porque se especificó "AlwaysCreate".
          Aplicando tarea Touch a "cmTC_b837a.dir\\Debug\\cmTC_b837a.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_b837a.dir\\Debug\\\\" /Fd"cmTC_b837a.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
          Compilador de optimización de C/C++ de Microsoft (R) versión 19.37.32822 para x64
          (C) Microsoft Corporation. Todos los derechos reservados.
          CMakeCCompilerABI.c
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_b837a.dir\\Debug\\\\" /Fd"cmTC_b837a.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\Jefe Maestro\\Desktop\\server\\CMakeFiles\\CMakeScratch\\TryCompile-rc1aav\\Debug\\cmTC_b837a.exe" /INCREMENTAL /ILK:"cmTC_b837a.dir\\Debug\\cmTC_b837a.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/Jefe Maestro/Desktop/server/CMakeFiles/CMakeScratch/TryCompile-rc1aav/Debug/cmTC_b837a.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/Jefe Maestro/Desktop/server/CMakeFiles/CMakeScratch/TryCompile-rc1aav/Debug/cmTC_b837a.lib" /MACHINE:X64  /machine:x64 cmTC_b837a.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_b837a.vcxproj -> C:\\Users\\Jefe Maestro\\Desktop\\server\\CMakeFiles\\CMakeScratch\\TryCompile-rc1aav\\Debug\\cmTC_b837a.exe
        FinalizeBuildStatus:
          Se eliminará el archivo "cmTC_b837a.dir\\Debug\\cmTC_b837a.tlog\\unsuccessfulbuild".
          Aplicando tarea Touch a "cmTC_b837a.dir\\Debug\\cmTC_b837a.tlog\\cmTC_b837a.lastbuildstate".
        Compilación del proyecto terminada "C:\\Users\\Jefe Maestro\\Desktop\\server\\CMakeFiles\\CMakeScratch\\TryCompile-rc1aav\\cmTC_b837a.vcxproj" (destinos predeterminados).
        
        Compilación correcta.
            0 Advertencia(s)
            0 Errores
        
        Tiempo transcurrido 00:00:03.58
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:7 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/Jefe Maestro/Desktop/server/CMakeFiles/CMakeScratch/TryCompile-c6wppw"
      binary: "C:/Users/Jefe Maestro/Desktop/server/CMakeFiles/CMakeScratch/TryCompile-c6wppw"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Jefe Maestro/Desktop/server/CMakeFiles/CMakeScratch/TryCompile-c6wppw'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_df90f.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        Versión de MSBuild 17.7.2+d6990bcfa para .NET Framework
        Compilación iniciada a las 3/9/2023 17:46:39.
        
        Proyecto "C:\\Users\\Jefe Maestro\\Desktop\\server\\CMakeFiles\\CMakeScratch\\TryCompile-c6wppw\\cmTC_df90f.vcxproj" en nodo 1 (destinos predeterminados).
        PrepareForBuild:
          Creando directorio "cmTC_df90f.dir\\Debug\\".
          Creando directorio "C:\\Users\\Jefe Maestro\\Desktop\\server\\CMakeFiles\\CMakeScratch\\TryCompile-c6wppw\\Debug\\".
          Creando directorio "cmTC_df90f.dir\\Debug\\cmTC_df90f.tlog\\".
        InitializeBuildStatus:
          Se creará "cmTC_df90f.dir\\Debug\\cmTC_df90f.tlog\\unsuccessfulbuild" porque se especificó "AlwaysCreate".
          Aplicando tarea Touch a "cmTC_df90f.dir\\Debug\\cmTC_df90f.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_df90f.dir\\Debug\\\\" /Fd"cmTC_df90f.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
          Compilador de optimización de C/C++ de Microsoft (R) versión 19.37.32822 para x64
          (C) Microsoft Corporation. Todos los derechos reservados.
          CMakeCXXCompilerABI.cpp
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_df90f.dir\\Debug\\\\" /Fd"cmTC_df90f.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\Jefe Maestro\\Desktop\\server\\CMakeFiles\\CMakeScratch\\TryCompile-c6wppw\\Debug\\cmTC_df90f.exe" /INCREMENTAL /ILK:"cmTC_df90f.dir\\Debug\\cmTC_df90f.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/Jefe Maestro/Desktop/server/CMakeFiles/CMakeScratch/TryCompile-c6wppw/Debug/cmTC_df90f.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/Jefe Maestro/Desktop/server/CMakeFiles/CMakeScratch/TryCompile-c6wppw/Debug/cmTC_df90f.lib" /MACHINE:X64  /machine:x64 cmTC_df90f.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_df90f.vcxproj -> C:\\Users\\Jefe Maestro\\Desktop\\server\\CMakeFiles\\CMakeScratch\\TryCompile-c6wppw\\Debug\\cmTC_df90f.exe
        FinalizeBuildStatus:
          Se eliminará el archivo "cmTC_df90f.dir\\Debug\\cmTC_df90f.tlog\\unsuccessfulbuild".
          Aplicando tarea Touch a "cmTC_df90f.dir\\Debug\\cmTC_df90f.tlog\\cmTC_df90f.lastbuildstate".
        Compilación del proyecto terminada "C:\\Users\\Jefe Maestro\\Desktop\\server\\CMakeFiles\\CMakeScratch\\TryCompile-c6wppw\\cmTC_df90f.vcxproj" (destinos predeterminados).
        
        Compilación correcta.
            0 Advertencia(s)
            0 Errores
        
        Tiempo transcurrido 00:00:03.50
        
      exitCode: 0
...
